### ISSUE TITLE
test(fine-grained): 3 failures under TEST_NATIVE_TYPE_KERNEL=1 differential — native-solved callee loses definition/note — pre-existing

### ISSUE THREAD

**Issue by Jonathangadeaharder** [codenkirch/mypy-rs#1146]
Discovered while gating #1115 (ran the fine-grained/daemon/cache suites with the kernel differential env on). All 3 fail on pristine `main` (`fce6fa14d`) with `TEST_NATIVE_TYPE_KERNEL=1 TEST_NATIVE_PARSER=1 TEST_NATIVE_RESOLVER=1`; they pass without `TEST_NATIVE_TYPE_KERNEL` (the harness overrides `options.native_type_kernel` from env in mypy/test/helpers.py:416, so this differential is opt-in).

Failures (all missing-note / variance-output divergences, same set on main and on the #1115 branch):

- `fine-grained.test::testGenericFineCallableNamed`
- `fine-grained.test::testGenericFineCallableNamed_cached`
- `fine-grained-python312.test::testPEP695VarianceChangesDueToDependency`

Diagnosed root cause for `testGenericFineCallableNamed`: `rust_solve_generic_call` (checkexpr.py:2982) returns a wire-decoded CallableType with `name = None` and `definition = None`. `_TypeRefFixer._match_definition` (wirefixup.py) only re-links `definition` when `t.name is not None`, so the re-link never fires for solved callees. `Messages.note_defined_here` (messages.py:1288) requires `callee.definition` and silently drops the `Called function defined in "c"` note, so the expected output `a.py:2: note: Called function defined in "c"` is missing.

Fix direction: give the solve-shim decode path a name/definition re-link (either propagate the callee name through the solve wire result, or match the fallback TypeInfo symbol table like `_match_definition` does with the pre-solve callee name). The PEP695 variance case likely shares the decoded-callee provenance gap but was not bisected.

Repro:
```bash
PYTHONPATH=<type_kernel dir>:<resolver dir>:<ast dir> TEST_NATIVE_TYPE_KERNEL=1 TEST_NATIVE_PARSER=1 TEST_NATIVE_RESOLVER=1 \
  uv run python -m pytest -n0 mypy/test/testfinegrained.py -k testGenericFineCallableNamed
```

**Comment by Jonathangadeaharder** [comment]
Reproduced on current `main` (`5dbfa31b7`) with freshly built extension `.so`s (type_kernel rebuilt 2026-08-29 06:20, no Rust sources newer than the binaries). Still open. Note: a wave-8 gate run that reported 0 fine-grained failures must have run without `TEST_NATIVE_TYPE_KERNEL=1` — the differential is opt-in (`mypy/test/helpers.py` overrides `options.native_type_kernel` from env after option parsing).

## Exact test ids (as pytest resolves them on 5dbfa31b7)

- `mypy/test/testfinegrained.py::FineGrainedSuite::fine-grained.test::testGenericFineCallableNamed`
- `mypy/test/testfinegrainedcache.py::FineGrainedCacheSuite::fine-grained.test::testGenericFineCallableNamed_cached`
- `mypy/test/testfinegrained.py::FineGrainedSuite::fine-grained-python312.test::testPEP695VarianceChangesDueToDependency`

(`_cached` lives in `testfinegrainedcache.py`, not `testfinegrained.py`; the python312 case is collected by `testfinegrained.py` from `test-data/unit/fine-grained-python312.test`.)

## Minimal repro (-n0, full differential)

```bash
cd /Users/jonathangadeaharder/projects/coding-utils/mypy-rs && \
PYTHONPATH=/private/tmp/mypy-rs-local-typekernel:/private/tmp/mypy-rs-local-resolver:/private/tmp/mypy-rs-local-ast \
TEST_NATIVE_TYPE_KERNEL=1 TEST_NATIVE_PARSER=1 TEST_NATIVE_RESOLVER=1 \
.venv/bin/python -m pytest -n0 \
  mypy/test/testfinegrained.py -k testGenericFineCallableNamed \
  mypy/test/testfinegrainedcache.py -k testGenericFineCallableNamed_cached \
  "mypy/test/testfinegrained.py::FineGrainedSuite::fine-grained-python312.test::testPEP695VarianceChangesDueToDependency"
```

## Run results on 5dbfa31b7

- All three tests: FAIL with the differential, matching the issue's divergences.
  - `testGenericFineCallableNamed` + `_cached` (`fine-grained.test:5248`): expected `a.py:2: note: Called function defined in "c"` missing — native-solved callee loses definition/name, consistent with the diagnosed `rust_solve_generic_call` wire-decode gap in the issue body.
  - `testPEP695VarianceChangesDueToDependency` (`fine-grained-python312.test:34`): expected `main:3: error: Incompatible types in assignment (expression has type "C[int]", variable has type "C[object]")` missing entirely (actual output empty).
- Negative control (same PYTHONPATH, `TEST_NATIVE_PARSER=1 TEST_NATIVE_RESOLVER=1`, no `TEST_NATIVE_TYPE_KERNEL`): all 3 pass.
- Kernel-only combo (`TEST_NATIVE_TYPE_KERNEL=1` alone, no parser/resolver env): still fails — the kernel differential alone is sufficient; parser/resolver opts are not required.
- Full sweep with `-n4` under the full differential: `3 failed, 1293 passed, 256 skipped` across `testfinegrained.py` + `testfinegrainedcache.py` — failure set is exactly these 3, no additional regressions.

**Comment by Jonathangadeaharder** [comment]
Diagnosed and fixed via #1174 (two distinct mechanisms behind the reported failures):

**1. `testPEP695VarianceChangesDueToDependency` — wrong variance pinned during daemon mid-propagation.**

Daemon mid-propagation calls `_build_native_resolvers([])` with an empty SCC (`update.py:723`, `update.py:1123`) while `self.modules` is transitional: fine-grained reuse keeps the previous round's `TypeInfo` for `a.C` in the module symbol table (merge_asts identity preservation + `fixup.py` relink), while reused member `Var`s (cross-round snapshot Var nodes) were rebound during reprocess to the *new* round's info. The variance pre-infer introduced with #1098 ran `infer_class_variances` on the old info against this incoherent pair: `f`'s member type got folded through `map_instance_to_supertype(C[T], node.info=new a.C)`, the fast path missed, `Any` fell back, `b.A[Any]` satisfied both co- and contravariance, and a wrong (covariant) variance got pinned on the *retained* info. The checker's later lazy `infer_class_variances` (checker.py:4021) then skipped the class because variance was no longer `VARIANCE_NOT_READY`, so the wrong answer stuck. With the kernel off, control computes variance lazily in the checker on the old-but-consistent state and gets it right.

Fix: guard the pre-infer loop with `if scc:` in `mypy/build.py` (`_build_native_resolvers`). Mid-propagation rounds carry variance as `VARIANCE_NOT_READY` in the snapshot and native seams defer to Python there, which is the intended safe fallback.

**2. `testGenericFineCallableNamed(_cached)` — fine-grained notes lost on generic callees.**

The native `infer_function_type_arguments` solve shim replaced the callee wholesale with the wire round-trip result (`callee = resolved_callee` in `mypy/checkexpr.py`), dropping `name`/`definition`/`line`/`column` provenance the Python path preserves on its copy: the "Called function defined here" fine-grained note hangs off `definition`, and AstNode contexts use line/column. Fix: restore provenance from the original callee via `copy_modified(...)`.

Verified with the 2-step dmypy scenario and the full differential gates (1296 + 10966 passed, self-check clean); see #1174.
